@baseUrl = http://localhost:7080/api/v1
@adminUsername = admin1
@adminPassword = admin12
@userUsername = user12
@userPassword = test12


### Create User - this one will only get a USER role by default
POST {{baseUrl}}/auth/register/

{
    "username": "user12",
    "password": "test12"
}

> {% client.global.set("token", response.body.token); %}

### USER login to get a token
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "{{userUsername}}",
  "password": "{{userPassword}}"
}

> {% client.global.set("token", response.body.token); %}


### Create Admin user
POST {{baseUrl}}/auth/register/

{
    "username": "admin1",
    "password": "admin12"
}

> {% client.global.set("token", response.body.token); %}

### ADMIN login to get a token
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}

> {% client.global.set("token", response.body.token); %}

###  Get
GET {{baseUrl}}/
Authorization: Bearer {{token}}

### Get
GET {{baseUrl}}/
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "name": "Jonas",
  "email": "jonas@guide.dk",
  "phoneNumber": 12345678,
  "experienceInYears": 5
}

###
PUT {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json


### Delete
DELETE {{baseUrl}}/
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Beach trip",
  "startTime": "2025-11-01T09:00:00",
  "endTime": "2025-11-01T17:00:00",
  "locationCordinates": "57.048",
  "price": 5000,
  "category": "BEACH"
}

###
PUT {{baseUrl}}/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "price": 7000
}

###
PUT {{baseUrl}}/
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/
Authorization: Bearer {{token}}

### Get
GET {{baseUrl}}/
Authorization: Bearer {{token}}

### Delete
DELETE {{baseUrl}}/
Authorization: Bearer {{token}}

### Get
GET {{baseUrl}}/
Authorization: Bearer {{token}}

### Get
GET {{baseUrl}}/
Authorization: Bearer {{token}}